version: '2'
services:
  app:
    build:
      context: .
      args:
        - ENV=test
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - URL_PORT=80
      - URL_HOST=0.0.0.0
      - SECRET_KEY_BASE=akFGnO4hgA0z4u51E9zm2F0vlMS4oQZqYqDSYz+h9chYGeS8D0c6EfYBv44wzStd
    ports:
      - "4000:4001"
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.3
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
